version: "3"

services:
  php:
    platform: linux/x86_64
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    environment:
      #DB_CONNECTION: mysql
      #DB_HOST: mysql
      #DB_PORT: 3306
      #DB_DATABASE: laravel
      #DB_USERNAME: user
      #DB_PASSWORD: root
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: root

    volumes:
      - ./src:/var/www/html
      
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  #mysql:
  #  platform: linux/x86_64
  #  image: mysql:5.7
  #  container_name: mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: laravel
  #    MYSQL_USER: user
  #    MYSQL_PASSWORD: root
  #    TZ: "Asia/Tokyo"
  #  volumes:
  #    - ./volumes/db/data:/var/lib/mysql
  #    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #  ports:
  #    - 3306:3306

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_DB: 'laravel'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'root'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin
  #  volumes:
  #    - ./volumes/pgadmin:/var/lib/pgadmin
  #  ports:
  #    - "8000:80"
  #  environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - postgres

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  container_name: phpmyadmin
  #  environment:
  #    - PMA_ARBITRARY=1
  #    - PMA_HOST=mysql
  #    - PMA_USER=root
  #    - PMA_PASSWORD=root
  #  ports:
  #    - 4040:80
  #  depends_on:
  #    - db
  #  volumes:
  #    - ./volumes/phpmyadmin/sessions:/sessions
  #    - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini